//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 06:41:58 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/course-details", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.course_details;
